#pragma once
// jaal::meta::list — the type list every other type-level tool is built on.
//
// Design rules for this module (see DESIGN.md §2):
//   * no dependency on anything else in jaal
//   * queries are concepts or constexpr values, never class templates you
//     have to ::value
//   * everything is a fold expression or a single pack expansion, so the
//     cost is linear in pack size and there is no recursive instantiation
//     depth to blow

#include <cstddef>
#include <type_traits>
#include <utility>

namespace jaal::meta {

// Type equality without instantiating a template per pair.
//
// std::is_same_v<A, B> is a variable template: every distinct (A, B) pair
// is a new instantiation the compiler must create and memoise. Pairwise
// queries (unique, dedup) do n² comparisons, and paying an instantiation
// for each one made a 600-element unique<> take 38 s on GCC 16; the builtin
// cut that to 15 s. MSVC lacks it; fall back.
//
// Complexity, n = list size:
//   size, at, member_of, index_of, concat, transform, filter   O(n)
//   unique, dedup, subset_of, minus, same_set                   O(n²) comparisons
// Pairwise ops are fine for effect rows (~10-30 entries). Don't feed them
// hundreds of types.
#if defined(__clang__) || defined(__GNUC__)
#  define JAAL_SAME(A, B) __is_same(A, B)
#else
#  define JAAL_SAME(A, B) std::is_same_v<A, B>
#endif

template <class... Ts>
struct list {
    static constexpr std::size_t size = sizeof...(Ts);
};

// ── is_list ──────────────────────────────────────────────────────────────
template <class T>     inline constexpr bool is_list_v = false;
template <class... Ts> inline constexpr bool is_list_v<list<Ts...>> = true;

template <class T>
concept type_list = is_list_v<T>;

// ── size ─────────────────────────────────────────────────────────────────
template <type_list L>
inline constexpr std::size_t size_v = L::size;

// ── contains / member_of ─────────────────────────────────────────────────
template <class L, class T> inline constexpr bool contains_v = false;
template <class... Ts, class T>
inline constexpr bool contains_v<list<Ts...>, T> = (JAAL_SAME(T, Ts) || ...);

template <class T, class L>
concept member_of = type_list<L> && contains_v<L, T>;

// ── count ────────────────────────────────────────────────────────────────
template <class L, class T> inline constexpr std::size_t count_v = 0;
template <class... Ts, class T>
inline constexpr std::size_t count_v<list<Ts...>, T> =
    (std::size_t{0} + ... + std::size_t{JAAL_SAME(T, Ts)});

// ── unique ───────────────────────────────────────────────────────────────
// Quadratic in the number of COMPARISONS (inherent), but still a single
// pack expansion: no instantiation depth.
template <class L> inline constexpr bool unique_v = false;
template <class... Ts>
inline constexpr bool unique_v<list<Ts...>> =
    ((count_v<list<Ts...>, Ts> == 1) && ...);

template <class L>
concept unique = type_list<L> && unique_v<L>;

// ── subset_of ────────────────────────────────────────────────────────────
template <class A, class B> inline constexpr bool subset_v = false;
template <class... As, class B>
inline constexpr bool subset_v<list<As...>, B> = (contains_v<B, As> && ...);

template <class A, class B>
concept subset_of = type_list<A> && type_list<B> && subset_v<A, B>;

// Same members, any order, duplicates ignored.
template <class A, class B>
concept same_set = subset_of<A, B> && subset_of<B, A>;

// ── index_of ─────────────────────────────────────────────────────────────
// Position of the FIRST occurrence; size_v<L> if absent. Computed with a
// constexpr loop over a bool array: no recursion, no pack indexing needed.
namespace detail {
template <class T, class... Ts>
consteval std::size_t index_of_impl() {
    constexpr bool hits[] = {JAAL_SAME(T, Ts)..., false};
    for (std::size_t i = 0; i < sizeof...(Ts); ++i)
        if (hits[i]) return i;
    return sizeof...(Ts);
}
}  // namespace detail

template <class L, class T> inline constexpr std::size_t index_of_v = 0;
template <class... Ts, class T>
inline constexpr std::size_t index_of_v<list<Ts...>, T> =
    detail::index_of_impl<T, Ts...>();

// ── at ───────────────────────────────────────────────────────────────────
// C++26 pack indexing when available; otherwise a flat overload set (one
// overload per element, all generated by ONE expansion), still no recursion.
namespace detail {
#if defined(__cpp_pack_indexing) && __cpp_pack_indexing >= 202311L
template <std::size_t I, class... Ts>
using at_impl = Ts...[I];
#else
template <std::size_t I, class T> struct indexed { using type = T; };
template <class Seq, class... Ts> struct indexer;
template <std::size_t... Is, class... Ts>
struct indexer<std::index_sequence<Is...>, Ts...> : indexed<Is, Ts>... {};
template <std::size_t I, class T>
auto select(indexed<I, T>) -> T;
template <std::size_t I, class... Ts>
using at_impl = decltype(select<I>(
    indexer<std::index_sequence_for<Ts...>, Ts...>{}));
#endif
}  // namespace detail

template <class L, std::size_t I> struct at;
template <class... Ts, std::size_t I>
    requires(I < sizeof...(Ts))
struct at<list<Ts...>, I> {
    using type = detail::at_impl<I, Ts...>;
};
template <class L, std::size_t I>
using at_t = typename at<L, I>::type;

// ── apply ────────────────────────────────────────────────────────────────
// Rebind a list's elements into another template: apply_t<std::variant, L>.
template <template <class...> class F, class L> struct apply;
template <template <class...> class F, class... Ts>
struct apply<F, list<Ts...>> {
    using type = F<Ts...>;
};
template <template <class...> class F, class L>
using apply_t = typename apply<F, L>::type;

}  // namespace jaal::meta
